version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mssql://192.168.100.95:1433/JCC
      SPRING_R2DBC_USERNAME: sa
      SPRING_R2DBC_PASSWORD: P@ssw0rd00
